In [2]:
using CSV
using DataFrames
using MLJ

In [3]:
# Read the CSV file into a DataFrame
df = CSV.read("megaGymDataset.csv", DataFrame)

# Display summary statistics of the DataFrame
describe(df)

9×7 DataFrame
 Row │ variable    mean     min                                median  max     ⋯
     │ Symbol      Union…   Any                                Union…  Any     ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ Column1     1458.5   0                                  1458.5  2917    ⋯
   2 │ Title                1.5-rep push-up                            Zercher
   3 │ Desc                 Adductor self-myofascial release…          With th
   4 │ Type                 Cardio                                     Strongm
   5 │ BodyPart             Abdominals                                 Triceps ⋯
   6 │ Equipment            Bands                                      Other
   7 │ Level                Beginner                                   Interme
   8 │ Rating      5.91969  0.0                                7.9     9.6
   9 │ RatingDesc           Average                                    Average ⋯
                                                               3 columns omitted

In [4]:
# Get the number of rows and columns in the DataFrame
nrow(df), ncol(df)

(2918, 9)

In [5]:
# Select the two columns from the original DataFrame
selected_columns = df[:, [:Title,  :BodyPart]]
# Create a new DataFrame with the selected columns
new_df = DataFrame(selected_columns)
nrow(new_df), ncol(new_df)

(2918, 2)

In [6]:
schema(new_df)

┌──────────┬──────────┬──────────┐
│ names    │ scitypes │ types    │
├──────────┼──────────┼──────────┤
│ Title    │ Textual  │ String   │
│ BodyPart │ Textual  │ String15 │
└──────────┴──────────┴──────────┘


In [7]:
last_df = unique(new_df; keep = :first)


2909×2 DataFrame
  Row │ Title                              BodyPart   
      │ String                             String15   
──────┼───────────────────────────────────────────────
    1 │ Partner plank band row             Abdominals
    2 │ Banded crunch isometric hold       Abdominals
    3 │ FYR Banded Plank Jack              Abdominals
    4 │ Banded crunch                      Abdominals
    5 │ Crunch                             Abdominals
    6 │ Decline band press sit-up          Abdominals
    7 │ FYR2 Banded Frog Pump              Abdominals
    8 │ Band low-to-high twist             Abdominals
    9 │ Barbell roll-out                   Abdominals
   10 │ Barbell Ab Rollout - On Knees      Abdominals
   11 │ Decline bar press sit-up           Abdominals
  ⋮   │                 ⋮                      ⋮
 2900 │ 30 Arms Close-Grip Push-Up         Triceps
 2901 │ 30 Arms BFR Close-Grip Push-Up     Triceps
 2902 │ Supine Chest Throw                 Triceps
 2903 │ Decline EZ-bar skullcrusher        Triceps
 2904 │ EZ-Bar Skullcrusher                Triceps
 2905 │ EZ-bar skullcrusher-               Triceps
 2906 │ Lying Close-Grip Barbell Triceps…  Triceps
 2907 │ EZ-Bar Skullcrusher - Gethin Var…  Triceps
 2908 │ TBS Skullcrusher                   Triceps
 2909 │ 30 Arms EZ-Bar Skullcrusher        Triceps
                                     2888 rows omitted

In [8]:
using DataFrames
# Reset the row indices of the DataFrame
last_df[!, :index] = 1:size(last_df, 1)

1:2909

In [9]:
using Flux

X = last_df.Title  # Exercise names

┌ Error: This version of CUDA.jl only supports NVIDIA drivers for CUDA 11.x or higher (yours is for CUDA 7.5.0)
└ @ CUDA C:\Users\LENOVO\.julia\packages\CUDA\p5OVK\src\initialization.jl:70


2909-element Vector{String}:
 "Partner plank band row"
 "Banded crunch isometric hold"
 "FYR Banded Plank Jack"
 "Banded crunch"
 "Crunch"
 "Decline band press sit-up"
 "FYR2 Banded Frog Pump"
 "Band low-to-high twist"
 "Barbell roll-out"
 "Barbell Ab Rollout - On Knees"
 "Decline bar press sit-up"
 "Bench barbell roll-out"
 "Barbell Side Bend"
 ⋮
 "FYR2 Triceps Push-Up"
 "30 Arms Triceps Dip"
 "30 Arms Close-Grip Push-Up"
 "30 Arms BFR Close-Grip Push-Up"
 "Supine Chest Throw"
 "Decline EZ-bar skullcrusher"
 "EZ-Bar Skullcrusher"
 "EZ-bar skullcrusher-"
 "Lying Close-Grip Barbell Triceps Press To Chin"
 "EZ-Bar Skullcrusher - Gethin Variation"
 "TBS Skullcrusher"
 "30 Arms EZ-Bar Skullcrusher"

In [10]:
y = last_df.BodyPart   # Target body parts

2909-element PooledArrays.PooledVector{String15, UInt32, Vector{UInt32}}:
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 "Abdominals"
 ⋮
 "Triceps"
 "Triceps"
 "Triceps"
 "Triceps"
 "Triceps"
 "Triceps"
 "Triceps"
 "Triceps"
 "Triceps"
 "Triceps"
 "Triceps"
 "Triceps"

In [11]:
# Step 2: Feature Extraction
X_encoded = Flux.onehotbatch(X, sort(unique(X))) |> Matrix{Float32}

2909×2909 Matrix{Float32}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0

In [13]:
# Encode target labels as integers
label_mapping = Dict(unique(y) .=> 1:length(unique(y)))
y_encoded = [label_mapping[label] for label in y] # Step 3: Model Training
# Split the data into training and testing sets
data = [(x, y) for (x, y) in zip(eachrow(X_encoded), y_encoded)] 

using Random

# Shuffle the data randomly
shuffled_data = shuffle(data)

# Define the desired train-test split ratio
train_ratio = 0.8

# Calculate the sizes of the training and test sets
train_size = Int(round(length(shuffled_data) * train_ratio))
test_size = length(shuffled_data) - train_size

# Split the data into training and test sets
train_data = shuffled_data[1:train_size]
test_data = shuffled_data[train_size+1:end]

582-element Vector{Tuple{SubArray{Float32, 1, Matrix{Float32}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}, Int64}}:
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 13)
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 1)
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 15)
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 2)
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 15)
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 12)
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 4)
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0

In [14]:
# Define the model architecture
input_size = size(X_encoded, 2)
model = Chain(
    Dense(input_size, 64, relu),
    Dense(64, 32, relu),
    Dense(32, length(label_mapping))
)

Chain(
  Dense(2909 => 64, relu),              # 186_240 parameters
  Dense(64 => 32, relu),                # 2_080 parameters
  Dense(32 => 17),                      # 561 parameters
)                   # Total: 6 arrays, 188_881 parameters, 738.191 KiB.

In [15]:
 # Define the loss function
loss(x, y) = Flux.crossentropy(softmax(model(x)), Flux.onehotbatch(y, 1:length(label_mapping)))
# Define the optimizer
optimizer = Flux.ADAM()

Adam(0.001, (0.9, 0.999), 1.0e-8, IdDict{Any, Any}())

In [16]:
# Train the model
for epoch in 1:10
    Flux.train!(loss, Flux.params(model), train_data, optimizer)
end

In [17]:
# Step 4: Model Evaluation
# Make predictions on the test set
X_test = [x for (x, _) in test_data]
y_test = [y for (_, y) in test_data]
y_pred = Flux.argmax(model.(X_test), dims=2)
# Calculate accuracy
accuracy = sum(y_pred .== reshape(y_test, :)') / length(y_test)

println("Accuracy: $accuracy")

Accuracy: 1.0


In [18]:
exercise_name = "Band low-to-high twist" # Example exercise name for prediction
exercise_encoded = Flux.onehotbatch([exercise_name], sort(unique(X_encoded))) |> Matrix{Float32}
predicted_body_part = Flux.argmax(model(exercise_encoded), dims=2)[1]

inverse_label_mapping = Dict(value => key for (key, value) in label_mapping)
predicted_body_part_label = inverse_label_mapping[predicted_body_part]

println("Predicted body part: $predicted_body_part_label")


LoadError: Value Band low-to-high twist not found in labels